### ISSUE TITLE
feature request: switch between characters

### ISSUE THREAD

**Issue by martinantonmueller** [acdh-oeaw/de-micro-editor#16]
In my source text I have several characters which are not in use in modern day German, e.g. "ſ" (Langes-s, Schaft-s), which nowadays is replaced with »s«, or »m̅« (»mm«) and »n̅« (»nn«). I would like to be able to toggle between the characters to give a historical and a new viewing possibility: 

The current encoding looks like this:
`<c rendition="#gemination-m">mm</c>`

I would like to use a slider and a possible solution I believe could work is if i actually had two elements, where the slider hides one and shows the other
`<span class="gemination-m old">m̅</span><span class="gemination-m new">mm</span>`

but what do I know?

**Comment by martinantonmueller** [comment]
I tried these tricks but they don't seem to work:
https://www.geeksforgeeks.org/how-to-replace-text-with-css/

**Comment by linxOD** [comment]
no new feature required. this can be done by using the approach mentioned in your blogpost: https://www.geeksforgeeks.org/how-to-replace-text-with-css/ with some slight adaptation.

when the `replaceMe` css gets added by clicking the slider the current symbol is hidden and `::after` holds the content for the new symbol. There is only one minor issue. `visibility: hidden` will hide the content but not the width*height of the content. I solved this by adding minus margin on the left but how much pts or px or else you have to add, depents on the font size of the text. 

```
.replaceMe {
    visibility: hidden;
}

.replaceMe:after {
    visibility: visible;
    content: 'ß';
    margin-left: -8pt;
}
```
