### ISSUE TITLE
Micro-Editor: Enable aot variant on default

### ISSUE THREAD

**Issue by StephanMa** [acdh-oeaw/de-micro-editor#24]
Dear all,
At first: well done!

is there a possibility to enable a "aot variant" on default? e.g. "all".

All the best
Stephan

**Comment by linxOD** [comment]
Dear Stephan,
thank you for your feedback!

I hope I understood your question correctly.
There are two Javascript events to enable the features e.g. AOT.
One: click
Second: onload

If you created all your variants and enabled the UP (urlparams) option e.g. `up: true`
```
var editor = new LoadEditor({
  aot: {
    title: "Title",
    variants: [
      {...},
    ],
  ...
  },
  up: true,
});
```
the aot variants can be controlled with urlparams. e.g. ?variant_one=true&variant_two=true
If you want all variants to be enabled on pageload you have to add each variant as urlparam.
Once you set `up: true` and enable a variant on click you can also see the changes in the urlparams.

Does this answer your question?

**Comment by StephanMa** [comment]
Thank you very much...
Unfortunately yes.
So, we have to pass all the options to the URL Parms ... 
My hope was, that there may be a flag in JS to enable certain options on default.

something like 
```js
{
          opt: "ef",
          opt_slider: "entities-features-slider",
          title: "Alle",
          color: "red",
          -->default: true;<--
          html_class: "undefined",
          css_class: "undefined",
          chg_citation: "citation-url",
          hide: {
            hidden: false,
            class: "undefined",
          },
          features: {
            all: true,
            class: "features-1",
          },
        },
```

**Comment by linxOD** [comment]
Thank you @StephanMa  for pull request. Tested and works like a charm. New Release shortly!
